ALTER TABLE "booking_audit_events" DROP CONSTRAINT "booking_audit_events_type_valid";--> statement-breakpoint
ALTER TABLE "booking_occupancies" ADD COLUMN "revision_kind" varchar(16) DEFAULT 'INITIAL' NOT NULL;--> statement-breakpoint
ALTER TABLE "booking_occupancies" ADD COLUMN "revision_reason_category" varchar(32);--> statement-breakpoint
ALTER TABLE "booking_occupancies" ADD COLUMN "revision_note" text;--> statement-breakpoint
ALTER TABLE "booking_audit_events" ADD CONSTRAINT "booking_audit_events_type_valid" CHECK ("booking_audit_events"."event_type" in ('QUOTE_ACCEPTED', 'BOOKING_CREATED', 'BOOKING_SCHEDULED', 'BOOKING_RESCHEDULED', 'BOOKING_CANCELLED', 'TEAM_ASSIGNED', 'EQUIPMENT_ASSIGNED', 'SCHEDULE_REVIEW_REQUIRED', 'OCCUPANCY_RELEASED'));--> statement-breakpoint
ALTER TABLE "booking_occupancies" ADD CONSTRAINT "booking_occupancies_revision_kind_valid" CHECK ("booking_occupancies"."revision_kind" in ('INITIAL', 'RESCHEDULE'));--> statement-breakpoint
ALTER TABLE "booking_occupancies" ADD CONSTRAINT "booking_occupancies_revision_reason_valid" CHECK ("booking_occupancies"."revision_reason_category" is null or "booking_occupancies"."revision_reason_category" in ('CUSTOMER_REQUEST', 'OPERATIONAL', 'TEAM_UNAVAILABLE', 'EQUIPMENT_UNAVAILABLE', 'TRAVEL_CONFLICT', 'OTHER'));--> statement-breakpoint
ALTER TABLE "booking_occupancies" ADD CONSTRAINT "booking_occupancies_revision_consistent" CHECK (("booking_occupancies"."revision_kind" = 'INITIAL' and "booking_occupancies"."previous_occupancy_id" is null and "booking_occupancies"."revision_reason_category" is null and "booking_occupancies"."revision_note" is null) or ("booking_occupancies"."revision_kind" = 'RESCHEDULE' and "booking_occupancies"."previous_occupancy_id" is not null and "booking_occupancies"."revision_reason_category" is not null));--> statement-breakpoint
ALTER TABLE "booking_occupancies" ADD CONSTRAINT "booking_occupancies_revision_note_valid" CHECK ("booking_occupancies"."revision_note" is null or (length(trim("booking_occupancies"."revision_note")) between 1 and 500));--> statement-breakpoint
ALTER TABLE "booking_occupancies" ADD CONSTRAINT "booking_occupancies_other_revision_note_required" CHECK ("booking_occupancies"."revision_reason_category" is distinct from 'OTHER' or "booking_occupancies"."revision_note" is not null);