import type {
  AppointmentWindowDefinition,
  EquipmentResourceDefinition,
  OperationsTeamDefinition,
  SchedulingPolicyDefinition,
  ServiceAreaDefinition,
  TravelTimeProfileDefinition,
  WeekdayCode,
  WorkingHourPolicyDefinition,
} from "./types";

export const developmentServiceAreas: readonly ServiceAreaDefinition[] = [
  {
    code: "SOFIA_CORE",
    name: { bg: "Централна София", en: "Sofia core" },
    active: true,
    serviceEligible: true,
    minimumOrderOverrideMinorUnits: null,
    estimatedBaseTravelMinutes: null,
    manualConfirmationRequired: false,
    geographicMetadata: null,
    notes:
      "Development classification only; exact district and geographic boundaries require owner approval.",
  },
  {
    code: "SOFIA_EXTENDED",
    name: { bg: "Разширена София", en: "Sofia extended" },
    active: true,
    serviceEligible: true,
    minimumOrderOverrideMinorUnits: null,
    estimatedBaseTravelMinutes: null,
    manualConfirmationRequired: true,
    geographicMetadata: null,
    notes:
      "Service may be operationally possible, but zone classification and commercial terms require confirmation.",
  },
  {
    code: "SOFIA_OUTSKIRTS",
    name: { bg: "Покрайнини на София", en: "Sofia outskirts" },
    active: true,
    serviceEligible: true,
    minimumOrderOverrideMinorUnits: null,
    estimatedBaseTravelMinutes: null,
    manualConfirmationRequired: true,
    geographicMetadata: null,
    notes:
      "Provisional service-area label only; boundaries, surcharge and minimum-order policy are unresolved.",
  },
  {
    code: "OUTSIDE_SOFIA",
    name: { bg: "Извън София", en: "Outside Sofia" },
    active: true,
    serviceEligible: false,
    minimumOrderOverrideMinorUnits: null,
    estimatedBaseTravelMinutes: null,
    manualConfirmationRequired: true,
    geographicMetadata: null,
    notes:
      "No standard automatic scheduling; every request requires manual operational and commercial review.",
  },
];

export const developmentTravelTimeProfile: TravelTimeProfileDefinition = {
  id: "development-travel-profile-v1",
  code: "SOFIA_TRAVEL_V1_DRAFT",
  name: "Sofia deterministic travel assumptions V1 draft",
  market: "SOFIA",
  version: 1,
  status: "DRAFT",
  effectiveFrom: null,
  effectiveUntil: null,
  defaultTravelMinutes: 45,
  interJobBufferMinutes: 10,
  provisional: true,
  active: false,
  rules: [
    {
      id: "SOFIA_TRAVEL_V1_CORE_SAME_AREA",
      originZoneCode: "SOFIA_CORE",
      destinationZoneCode: "SOFIA_CORE",
      estimatedTravelMinutes: 15,
      bidirectional: true,
      sameDistrictOnly: true,
      manualAssessmentRequired: false,
      priority: 10,
      active: true,
      notes: "Same normalized core district development fallback.",
    },
    {
      id: "SOFIA_TRAVEL_V1_CORE_CORE",
      originZoneCode: "SOFIA_CORE",
      destinationZoneCode: "SOFIA_CORE",
      estimatedTravelMinutes: 20,
      bidirectional: true,
      sameDistrictOnly: false,
      manualAssessmentRequired: false,
      priority: 20,
      active: true,
      notes: "Different or unspecified Sofia-core areas.",
    },
    {
      id: "SOFIA_TRAVEL_V1_CORE_EXTENDED",
      originZoneCode: "SOFIA_CORE",
      destinationZoneCode: "SOFIA_EXTENDED",
      estimatedTravelMinutes: 30,
      bidirectional: true,
      sameDistrictOnly: false,
      manualAssessmentRequired: false,
      priority: 30,
      active: true,
      notes: "Core to extended-zone development fallback.",
    },
    {
      id: "SOFIA_TRAVEL_V1_EXTENDED_EXTENDED",
      originZoneCode: "SOFIA_EXTENDED",
      destinationZoneCode: "SOFIA_EXTENDED",
      estimatedTravelMinutes: 30,
      bidirectional: true,
      sameDistrictOnly: false,
      manualAssessmentRequired: false,
      priority: 40,
      active: true,
      notes: "Within the unresolved extended-zone label.",
    },
    {
      id: "SOFIA_TRAVEL_V1_CORE_OUTSKIRTS",
      originZoneCode: "SOFIA_CORE",
      destinationZoneCode: "SOFIA_OUTSKIRTS",
      estimatedTravelMinutes: 40,
      bidirectional: true,
      sameDistrictOnly: false,
      manualAssessmentRequired: false,
      priority: 50,
      active: true,
      notes: "Core to outskirts development fallback.",
    },
    {
      id: "SOFIA_TRAVEL_V1_EXTENDED_OUTSKIRTS",
      originZoneCode: "SOFIA_EXTENDED",
      destinationZoneCode: "SOFIA_OUTSKIRTS",
      estimatedTravelMinutes: 45,
      bidirectional: true,
      sameDistrictOnly: false,
      manualAssessmentRequired: false,
      priority: 60,
      active: true,
      notes: "Extended-zone to outskirts development fallback.",
    },
    {
      id: "SOFIA_TRAVEL_V1_OUTSKIRTS_OUTSKIRTS",
      originZoneCode: "SOFIA_OUTSKIRTS",
      destinationZoneCode: "SOFIA_OUTSKIRTS",
      estimatedTravelMinutes: 45,
      bidirectional: true,
      sameDistrictOnly: false,
      manualAssessmentRequired: false,
      priority: 70,
      active: true,
      notes: "Within the unresolved outskirts-zone label.",
    },
  ],
};

export const developmentWorkingHourPolicy: WorkingHourPolicyDefinition = {
  id: "development-working-hours-v1",
  code: "SOFIA_TEAM_HOURS_V1_DRAFT",
  name: "Sofia team operating window V1 draft",
  timeZone: "Europe/Sofia",
  version: 1,
  status: "DRAFT",
  effectiveFrom: null,
  effectiveUntil: null,
  provisional: true,
  active: false,
  rules: Array.from({ length: 7 }, (_, index) => {
    const weekday = (index + 1) as WeekdayCode;
    return {
      id: `SOFIA_TEAM_HOURS_V1_WEEKDAY_${weekday}`,
      weekday,
      startMinute: 6 * 60,
      endMinute: 22 * 60,
      enabled: true,
      teamCode: null,
    };
  }),
};

export const developmentAppointmentWindows: readonly AppointmentWindowDefinition[] = [
  {
    id: "SOFIA_WINDOWS_V1_EARLY_MORNING",
    profileCode: "SOFIA_APPOINTMENT_WINDOWS_V1_DRAFT",
    version: 1,
    status: "DRAFT",
    windowCode: "EARLY_MORNING",
    name: { bg: "Рано сутрин", en: "Early morning" },
    startMinute: 6 * 60,
    endMinute: 9 * 60,
    provisional: true,
    active: false,
  },
  {
    id: "SOFIA_WINDOWS_V1_MORNING",
    profileCode: "SOFIA_APPOINTMENT_WINDOWS_V1_DRAFT",
    version: 1,
    status: "DRAFT",
    windowCode: "MORNING",
    name: { bg: "Сутрин", en: "Morning" },
    startMinute: 9 * 60,
    endMinute: 12 * 60,
    provisional: true,
    active: false,
  },
  {
    id: "SOFIA_WINDOWS_V1_MIDDAY",
    profileCode: "SOFIA_APPOINTMENT_WINDOWS_V1_DRAFT",
    version: 1,
    status: "DRAFT",
    windowCode: "MIDDAY",
    name: { bg: "По обяд", en: "Midday" },
    startMinute: 12 * 60,
    endMinute: 15 * 60,
    provisional: true,
    active: false,
  },
  {
    id: "SOFIA_WINDOWS_V1_AFTERNOON",
    profileCode: "SOFIA_APPOINTMENT_WINDOWS_V1_DRAFT",
    version: 1,
    status: "DRAFT",
    windowCode: "AFTERNOON",
    name: { bg: "Следобед", en: "Afternoon" },
    startMinute: 15 * 60,
    endMinute: 18 * 60,
    provisional: true,
    active: false,
  },
  {
    id: "SOFIA_WINDOWS_V1_EVENING",
    profileCode: "SOFIA_APPOINTMENT_WINDOWS_V1_DRAFT",
    version: 1,
    status: "DRAFT",
    windowCode: "EVENING",
    name: { bg: "Вечер", en: "Evening" },
    startMinute: 18 * 60,
    endMinute: 22 * 60,
    provisional: true,
    active: false,
  },
];

export const developmentEquipmentResources: readonly EquipmentResourceDefinition[] = [
  {
    id: "development-cleaning-machine-a",
    code: "CLEANING_MACHINE_A",
    name: "Development cleaning machine A",
    equipmentTypeCode: "PORTABLE_CLEANING_MACHINE",
    capabilityCode: "PORTABLE_EXTRACTION",
    status: "ACTIVE",
    active: true,
    assignedTeamCode: "TEAM_A",
    serialNumber: null,
    notes: "Neutral development resource; no manufacturer or specification claim.",
  },
  {
    id: "development-cleaning-machine-b",
    code: "CLEANING_MACHINE_B",
    name: "Development cleaning machine B",
    equipmentTypeCode: "PORTABLE_CLEANING_MACHINE",
    capabilityCode: "PORTABLE_EXTRACTION",
    status: "ACTIVE",
    active: true,
    assignedTeamCode: "TEAM_B",
    serialNumber: null,
    notes: "Neutral development resource; no manufacturer or specification claim.",
  },
];

export const developmentTeams: readonly OperationsTeamDefinition[] = [
  {
    id: "development-team-a",
    code: "TEAM_A",
    name: "Development Team A",
    active: true,
    defaultCrewSize: 2,
    workingHourPolicyCode: developmentWorkingHourPolicy.code,
    capabilityCodes: [
      "STANDARD_RESIDENTIAL",
      "COMMERCIAL_AREA",
      "PORTABLE_EXTRACTION",
    ],
    equipmentResourceCodes: ["CLEANING_MACHINE_A"],
    notes: "Development capacity fixture only; no employee identities are stored.",
  },
  {
    id: "development-team-b",
    code: "TEAM_B",
    name: "Development Team B",
    active: true,
    defaultCrewSize: 2,
    workingHourPolicyCode: developmentWorkingHourPolicy.code,
    capabilityCodes: [
      "STANDARD_RESIDENTIAL",
      "COMMERCIAL_AREA",
      "PORTABLE_EXTRACTION",
    ],
    equipmentResourceCodes: ["CLEANING_MACHINE_B"],
    notes: "Development capacity fixture only; no employee identities are stored.",
  },
];

export const developmentSchedulingPolicy: SchedulingPolicyDefinition = {
  code: "SOFIA_SCHEDULING_V1_DRAFT",
  name: "Sofia scheduling assumptions V1 draft",
  version: 1,
  status: "DRAFT",
  effectiveFrom: null,
  effectiveUntil: null,
  provisional: true,
  active: false,
  candidateIntervalMinutes: 30,
  interJobBufferMinutes:
    developmentTravelTimeProfile.interJobBufferMinutes,
  largeJobReviewThresholdMinutes: 360,
};
