import type { AuthLocale } from "@/auth/validation";
import type { AccountStatus } from "@/modules/identity-access/authorization";
import type { ApplicationRoleCode } from "@/modules/identity-access/policy";

const shared = {
  bg: {
    backToUsers: "Назад към потребителите",
    cancel: "Отказ",
    confirm: "Потвърди",
    notAvailable: "Не е достъпно",
    never: "Няма",
    roleLabels: {
      OWNER: "Собственик",
      ADMIN: "Администратор",
      DISPATCHER: "Диспечер",
      TECHNICIAN: "Техник",
      CUSTOMER: "Клиент",
    },
    statusLabels: {
      ACTIVE: "Активен",
      SUSPENDED: "Временно спрян",
      DISABLED: "Деактивиран",
    },
  },
  en: {
    backToUsers: "Back to users",
    cancel: "Cancel",
    confirm: "Confirm",
    notAvailable: "Unavailable",
    never: "None",
    roleLabels: {
      OWNER: "Owner",
      ADMIN: "Administrator",
      DISPATCHER: "Dispatcher",
      TECHNICIAN: "Technician",
      CUSTOMER: "Customer",
    },
    statusLabels: {
      ACTIVE: "Active",
      SUSPENDED: "Suspended",
      DISABLED: "Disabled",
    },
  },
} as const satisfies Record<
  AuthLocale,
  {
    backToUsers: string;
    cancel: string;
    confirm: string;
    notAvailable: string;
    never: string;
    roleLabels: Record<ApplicationRoleCode, string>;
    statusLabels: Record<AccountStatus, string>;
  }
>;

export const adminContent = {
  bg: {
    ...shared.bg,
    list: {
      eyebrow: "Администрация",
      title: "Потребители",
      intro:
        "Преглед на приложните профили, достъпа и безопасното състояние на акаунтите.",
      search: "Име или идентификатор на профил",
      searchPlaceholder: "Търсене",
      status: "Статус",
      role: "Роля",
      all: "Всички",
      apply: "Приложи",
      clear: "Изчисти",
      empty: "Няма приложни профили, които отговарят на филтрите.",
      created: "Създаден",
      lastActivity: "Последна безопасна активност",
      locale: "Език",
      roles: "Роли",
      view: "Отвори профила",
      previous: "Предишна",
      next: "Следваща",
      pageSummary: (page: number, total: number) => `Страница ${page} · ${total} профила`,
      providerEmailUnavailable:
        "Търсене и показване по имейл не е активно, докато не бъде доказан ограничен достъп до Provider Admin API.",
    },
    detail: {
      eyebrow: "Привилегирован профил",
      profile: "Приложен профил",
      status: "Състояние на достъпа",
      roles: "Роли и история",
      audit: "Безопасна одитна история",
      provider: "Състояние при доставчика",
      sessions: "Сесии",
      displayName: "Име",
      locale: "Език",
      phone: "Телефон",
      created: "Създаден",
      assigned: "Зададена",
      revoked: "Отнета",
      current: "Активна",
      historical: "Историческа",
      noRoles: "Няма активна роля.",
      noAudit: "Няма безопасни одитни събития.",
      auditEventLabels: {
        SIGNUP_SUCCEEDED: "Успешна регистрация",
        LOGIN_SUCCEEDED: "Успешен вход",
        LOGIN_FAILED: "Неуспешен вход",
        LOGOUT_SUCCEEDED: "Успешен изход",
        PASSWORD_RESET_REQUESTED: "Поискано възстановяване на парола",
        PASSWORD_RESET_COMPLETED: "Паролата е възстановена",
        EMAIL_VERIFICATION_REQUESTED: "Поискано потвърждение на имейл",
        EMAIL_VERIFIED: "Имейлът е потвърден",
        ROLE_ASSIGNED: "Зададена роля",
        ROLE_REMOVED: "Отнета роля",
        ACCOUNT_STATUS_CHANGED: "Променен статус на акаунта",
        OWNER_BOOTSTRAPPED: "Създаден първи собственик",
      },
      auditOutcomeLabels: {
        SUCCESS: "Успех",
        FAILURE: "Неуспех",
        DENIED: "Отказано",
      },
      auditMetadataLabels: {
        reasonCode: "Причина",
        roleCode: "Роля",
        previousStatus: "Предишен статус",
        newStatus: "Нов статус",
        source: "Източник",
      },
      privilegedAdministration: "Привилегирована администрация",
      providerUnknown:
        "Състоянието не може да бъде потвърдено безопасно с текущите Provider Admin права.",
      providerAligned: "Профилът и идентичността при доставчика са свързани.",
      providerMissing: "Приложният профил няма намерена идентичност при доставчика.",
      sessionUnavailable:
        "Броят и отнемането на сесии са блокирани, докато Provider Admin достъпът и скорошното удостоверяване не бъдат доказани.",
      providerUserListing: "Списък на идентичности при доставчика",
      sessionListing: "Списък на сесии",
      revokeAllSessions: "Отнемане на всички сесии",
      supported: "Поддържа се; изисква Provider Admin",
      unavailableCapability: "Не е достъпно",
      highRiskGate:
        "Промяната е блокирана: доставчикът не предоставя надеждно скорошно повторно удостоверяване.",
      assignRole: "Задай роля",
      revokeRole: "Отнеми роля",
      changeStatus: "Промени статуса",
      suspend: "Спри временно",
      reactivate: "Активирай отново",
      disable: "Деактивирай",
      confirmationTitle: "Потвърдете привилегированото действие",
      confirmationBody:
        "Това действие променя достъпа и ще бъде записано в безопасния одитен журнал.",
      statusBody:
        "Статусът се прилага веднага от приложението и промяната се записва в одита.",
      notFound: "Профилът не е намерен.",
    },
    action: {
      success: "Промяната е приложена и записана.",
      noChange: "Няма промяна; текущото състояние вече съвпада.",
      forbidden: "Действието не е разрешено.",
      lastOwner: "Последният активен собственик е защитен.",
      unavailable: "Промяната временно не е достъпна.",
      invalid: "Заявката е невалидна.",
      rateLimited: "Действието временно е ограничено. Опитайте по-късно.",
      recentAuth: "Изисква се надеждно скорошно повторно удостоверяване.",
    },
  },
  en: {
    ...shared.en,
    list: {
      eyebrow: "Administration",
      title: "Users",
      intro: "Review application profiles, access roles, and safe account state.",
      search: "Name or profile identifier",
      searchPlaceholder: "Search",
      status: "Status",
      role: "Role",
      all: "All",
      apply: "Apply",
      clear: "Clear",
      empty: "No application profiles match these filters.",
      created: "Created",
      lastActivity: "Last safe activity",
      locale: "Language",
      roles: "Roles",
      view: "Open profile",
      previous: "Previous",
      next: "Next",
      pageSummary: (page: number, total: number) => `Page ${page} · ${total} profiles`,
      providerEmailUnavailable:
        "Email display and search remain off until narrowly scoped Provider Admin access is proven.",
    },
    detail: {
      eyebrow: "Privileged profile",
      profile: "Application profile",
      status: "Access status",
      roles: "Roles and history",
      audit: "Safe audit history",
      provider: "Provider state",
      sessions: "Sessions",
      displayName: "Display name",
      locale: "Language",
      phone: "Phone",
      created: "Created",
      assigned: "Assigned",
      revoked: "Revoked",
      current: "Active",
      historical: "Historical",
      noRoles: "No active role is assigned.",
      noAudit: "No safe audit events are available.",
      auditEventLabels: {
        SIGNUP_SUCCEEDED: "Signup succeeded",
        LOGIN_SUCCEEDED: "Login succeeded",
        LOGIN_FAILED: "Login failed",
        LOGOUT_SUCCEEDED: "Logout succeeded",
        PASSWORD_RESET_REQUESTED: "Password reset requested",
        PASSWORD_RESET_COMPLETED: "Password reset completed",
        EMAIL_VERIFICATION_REQUESTED: "Email verification requested",
        EMAIL_VERIFIED: "Email verified",
        ROLE_ASSIGNED: "Role assigned",
        ROLE_REMOVED: "Role revoked",
        ACCOUNT_STATUS_CHANGED: "Account status changed",
        OWNER_BOOTSTRAPPED: "First owner bootstrapped",
      },
      auditOutcomeLabels: {
        SUCCESS: "Success",
        FAILURE: "Failure",
        DENIED: "Denied",
      },
      auditMetadataLabels: {
        reasonCode: "Reason",
        roleCode: "Role",
        previousStatus: "Previous status",
        newStatus: "New status",
        source: "Source",
      },
      privilegedAdministration: "Privileged administration",
      providerUnknown:
        "Provider state cannot be verified safely with the current Provider Admin authority.",
      providerAligned: "The application profile and provider identity are linked.",
      providerMissing: "The application profile has no provider identity found.",
      sessionUnavailable:
        "Session counts and revocation are blocked until Provider Admin access and recent authentication are proven.",
      providerUserListing: "Provider identity listing",
      sessionListing: "Session listing",
      revokeAllSessions: "Revoke all sessions",
      supported: "Supported; Provider Admin required",
      unavailableCapability: "Unavailable",
      highRiskGate:
        "This change is blocked because the provider does not expose reliable recent reauthentication.",
      assignRole: "Assign role",
      revokeRole: "Revoke role",
      changeStatus: "Change status",
      suspend: "Suspend",
      reactivate: "Reactivate",
      disable: "Disable",
      confirmationTitle: "Confirm privileged action",
      confirmationBody:
        "This action changes access and will be appended to the safe audit history.",
      statusBody:
        "Application status takes effect immediately and the change is appended to the audit history.",
      notFound: "The profile was not found.",
    },
    action: {
      success: "The change was applied and audited.",
      noChange: "No change was needed; the state already matches.",
      forbidden: "This action is not permitted.",
      lastOwner: "The last active owner is protected.",
      unavailable: "The change is temporarily unavailable.",
      invalid: "The request is invalid.",
      rateLimited: "This action is temporarily limited. Try again later.",
      recentAuth: "Reliable recent reauthentication is required.",
    },
  },
} as const;
