import type { AuthLocale } from "@/auth/validation";
import type {
  AuthorityCategory,
  AuthorityEnvironmentScope,
  AuthorityEvidenceClass,
  AuthorityStatus,
  AuthorityType,
  ReadinessMatrixStatus,
} from "@/modules/business-authority/types";

const categoryLabels = {
  bg: {
    BRAND_CONTENT: "Бранд, контакти и твърдения",
    SERVICE_SCOPE: "Обхват на услугите",
    PRICING: "Ценообразуване",
    VAT_TAX: "ДДС и данъци",
    SELLER_LEGAL: "Продавач и правен профил",
    SCHEDULING: "График и наличност",
    TRAVEL: "Зони, пътуване и паркиране",
    TEAMS_EQUIPMENT: "Екипи и оборудване",
    AUTH: "Идентичност и сесии",
    PRIVACY_RETENTION: "Поверителност и съхранение",
    EMAIL: "Имейл и подател",
    MONITORING: "Мониторинг и ескалация",
    BACKUP_RECOVERY: "Архивиране и възстановяване",
    FINANCE_FISCAL: "Финанси и фискални правила",
    DATABASE: "Production база данни",
    DOMAIN_TLS: "Домейн, origins и TLS",
    DEPLOYMENT_AUTHORIZATION: "Разрешение за production",
  },
  en: {
    BRAND_CONTENT: "Brand, contacts, and claims",
    SERVICE_SCOPE: "Service scope",
    PRICING: "Pricing",
    VAT_TAX: "VAT and tax",
    SELLER_LEGAL: "Seller and legal profile",
    SCHEDULING: "Scheduling and availability",
    TRAVEL: "Zones, travel, and parking",
    TEAMS_EQUIPMENT: "Teams and equipment",
    AUTH: "Identity and sessions",
    PRIVACY_RETENTION: "Privacy and retention",
    EMAIL: "Email and sender",
    MONITORING: "Monitoring and escalation",
    BACKUP_RECOVERY: "Backup and recovery",
    FINANCE_FISCAL: "Finance and fiscal rules",
    DATABASE: "Production database",
    DOMAIN_TLS: "Domain, origins, and TLS",
    DEPLOYMENT_AUTHORIZATION: "Production authorization",
  },
} as const satisfies Record<AuthLocale, Record<AuthorityCategory, string>>;

const sharedLabels = {
  bg: {
    environments: {
      DEVELOPMENT: "Разработка",
      STAGING: "Staging",
      PRODUCTION: "Production",
    },
    evidence: {
      OWNER_INPUT: "Решение на собственика",
      SYSTEM_VERIFIED: "Системна проверка",
      EXTERNAL_EVIDENCE_REQUIRED: "Изисква външно доказателство",
    },
    statuses: {
      PROPOSED: "Предложено",
      UNDER_REVIEW: "В преглед",
      APPROVED_FOR_STAGING: "Одобрено за staging",
      APPROVED_FOR_PRODUCTION: "Одобрено за production",
      SUPERSEDED: "Заменено",
      REJECTED: "Отхвърлено",
    },
    authorityTypes: {
      OWNER: "Собственик",
      ACCOUNTANT: "Счетоводител",
      LEGAL: "Правен преглед",
      OPERATIONS: "Операции",
      TECHNICAL: "Технически преглед",
      CONTENT_CLAIMS: "Твърдения и съдържание",
    },
    matrixStatuses: {
      PASS: "Готово",
      OWNER_APPROVAL_REQUIRED: "Изисква собственик",
      ACCOUNTANT_APPROVAL_REQUIRED: "Изисква счетоводител",
      LEGAL_REVIEW_REQUIRED: "Изисква правен преглед",
      PROVIDER_LIMITATION: "Ограничение на доставчик",
      TECHNICAL_BLOCKER: "Технически блокер",
      NOT_AUTHORIZED: "Не е разрешено",
    },
  },
  en: {
    environments: {
      DEVELOPMENT: "Development",
      STAGING: "Staging",
      PRODUCTION: "Production",
    },
    evidence: {
      OWNER_INPUT: "Owner decision",
      SYSTEM_VERIFIED: "System verification",
      EXTERNAL_EVIDENCE_REQUIRED: "External evidence required",
    },
    statuses: {
      PROPOSED: "Proposed",
      UNDER_REVIEW: "Under review",
      APPROVED_FOR_STAGING: "Approved for staging",
      APPROVED_FOR_PRODUCTION: "Approved for production",
      SUPERSEDED: "Superseded",
      REJECTED: "Rejected",
    },
    authorityTypes: {
      OWNER: "Owner",
      ACCOUNTANT: "Accountant",
      LEGAL: "Legal review",
      OPERATIONS: "Operations",
      TECHNICAL: "Technical review",
      CONTENT_CLAIMS: "Content and claims",
    },
    matrixStatuses: {
      PASS: "Ready",
      OWNER_APPROVAL_REQUIRED: "Owner required",
      ACCOUNTANT_APPROVAL_REQUIRED: "Accountant required",
      LEGAL_REVIEW_REQUIRED: "Legal review required",
      PROVIDER_LIMITATION: "Provider limitation",
      TECHNICAL_BLOCKER: "Technical blocker",
      NOT_AUTHORIZED: "Not authorized",
    },
  },
} as const satisfies Record<
  AuthLocale,
  {
    environments: Record<AuthorityEnvironmentScope, string>;
    evidence: Record<AuthorityEvidenceClass, string>;
    statuses: Record<AuthorityStatus, string>;
    authorityTypes: Record<AuthorityType, string>;
    matrixStatuses: Record<ReadinessMatrixStatus, string>;
  }
>;

export const businessAuthorityContent = {
  bg: {
    ...sharedLabels.bg,
    categories: categoryLabels.bg,
    eyebrow: "Бизнес управление",
    title: "Оперативна готовност и бизнес правомощия",
    intro:
      "Единен регистър за решенията, доказателствата и изричните одобрения, необходими преди production. Историческите оферти, резервации, фактури и документи не се променят.",
    adminReadOnly:
      "Администраторите имат достъп само за преглед. Предложенията и решенията са защитени действия на активен собственик.",
    ownerNotice:
      "Това е привилегирован работен пакет. Одобрението за staging никога не разрешава production.",
    print: "Печат на пакета",
    generated: "Генерирано",
    readiness: "Пакет за разрешение",
    readinessIntro:
      "Готовността се извежда от валидни, действащи и пълно одобрени записи — не от отметка или ръчен статус.",
    ready: "Всички зависимости са одобрени за тази среда.",
    blocked: "Средата не е разрешена. Нерешените зависимости остават блокери.",
    approvedCount: "Одобрени",
    pendingCount: "Чакащи",
    blockers: "Блокери",
    noBlockers: "Няма блокери.",
    categorySummary: "Категории на готовност",
    registry: "Регистър на правомощията",
    registryIntro:
      "Показва проверените структурирани стойности, безопасните препратки и безопасните резюмета за всяка версия. Вътрешни бележки, идентификатори на доставчици, тайни и необработено съдържание на доказателства никога не се визуализират.",
    noRecord: "Няма запис",
    noItems: "Няма записи в тази група.",
    approvedItems: "Одобрени зависимости",
    pendingItems: "Чакащи зависимости",
    version: "Версия",
    currentReadinessVersion: "Текуща версия, избрана от проверката за готовност",
    latestVersion: "Последна версия",
    historicalVersion: "Историческа версия",
    latestPendingVersion:
      "Последна налична версия — не е избрана от проверката за готовност",
    environment: "Среда",
    effective: "В сила от",
    until: "В сила до",
    valueKind: "Тип стойност",
    evidenceClass: "Клас доказателство",
    evidencePresent: "Доказателство",
    evidenceAvailable: "Безопасна препратка е записана",
    evidenceMissing: "Няма записана препратка",
    governedValue: "Управлявана стойност",
    invalidValue: "Стойността не отговаря на текущия строг формат и не се показва.",
    sourceReference: "Безопасна препратка към източник",
    evidenceSummary: "Безопасно резюме на доказателството",
    notRecorded: "Не е записано",
    requiredApprovals: "Необходими правомощия",
    status: "Статус",
    proposal: {
      title: "Ново предложение",
      intro:
        "Само за собственик. JSON стойността се проверява стриктно според избраното правомощие; непознати полета и прекомерно съдържание се отхвърлят.",
      privileged: "Привилегирован редактор — не поставяйте тайни, токени, пароли или лични данни.",
      authority: "Правомощие",
      environment: "Изричен обхват",
      value: "Строга JSON стойност",
      valueHelp:
        "Използвайте само един от показаните типове за избраното правомощие. Статус, автор, одобряващ и системно доказателство не се приемат от браузъра.",
      sourceReference: "Безопасна препратка към източник",
      sourceHelp: "Не въвеждайте съдържанието на доказателството или идентификатор на доставчик.",
      evidenceSummary: "Безопасно резюме",
      internalNotes: "Вътрешна бележка (не се показва в пакета)",
      effectiveFrom: "В сила от",
      effectiveUntil: "В сила до (незадължително)",
      submit: "Създай предложение",
      pending: "Записване…",
    },
    actions: {
      submit: "Изпрати за преглед",
      approve: "Запиши одобрение",
      reject: "Отхвърли",
      confirmationTitle: "Потвърдете управленското действие",
      submitDescription: "Записът ще премине към формален преглед.",
      approveDescription:
        "Ще бъде записано отделно одобрение от избраното концептуално правомощие. Production остава блокиран до всички зависимости.",
      rejectDescription: "Записът ще стане терминално отхвърлен.",
      decisionAuthority: "Одобрение като",
      evidenceReference: "Безопасна препратка към доказателство",
      evidenceSummary: "Безопасно резюме",
      cancel: "Отказ",
      confirm: "Потвърди",
      pending: "Обработка…",
    },
    actionResult: {
      success: "Действието е записано в неизменяемия одит.",
      invalid: "Заявката е невалидна или съдържа непознати полета.",
      forbidden: "Действието не е разрешено.",
      conflict: "Записът е променен. Презаредете страницата и опитайте отново.",
      dependencies: "Production GO е блокирано от неодобрени зависимости.",
      unavailable: "Действието временно не е достъпно.",
      rateLimited: "Действието временно е ограничено. Опитайте по-късно.",
    },
  },
  en: {
    ...sharedLabels.en,
    categories: categoryLabels.en,
    eyebrow: "Business governance",
    title: "Operational readiness and business authority",
    intro:
      "One registry for the decisions, evidence, and explicit approvals required before production. Historical quotes, bookings, invoices, and documents are never rewritten.",
    adminReadOnly:
      "Administrators have read-only access. Proposals and decisions are protected actions for an active Owner.",
    ownerNotice:
      "This is a privileged working package. Staging approval never authorizes production.",
    print: "Print package",
    generated: "Generated",
    readiness: "Authorization package",
    readinessIntro:
      "Readiness is derived from valid, effective, fully approved records—not from a checkbox or client-provided status.",
    ready: "Every dependency is approved for this environment.",
    blocked: "The environment is not authorized. Unresolved dependencies remain blockers.",
    approvedCount: "Approved",
    pendingCount: "Pending",
    blockers: "Blockers",
    noBlockers: "No blockers.",
    categorySummary: "Readiness categories",
    registry: "Authority registry",
    registryIntro:
      "Shows validated structured values, safe references, and safe summaries for every version. Internal notes, provider identifiers, secrets, and raw evidence contents are never rendered.",
    noRecord: "No record",
    noItems: "No records in this group.",
    approvedItems: "Approved dependencies",
    pendingItems: "Pending dependencies",
    version: "Version",
    currentReadinessVersion: "Current readiness-selected version",
    latestVersion: "Latest version",
    historicalVersion: "Historical version",
    latestPendingVersion:
      "Latest available version—not selected by readiness",
    environment: "Environment",
    effective: "Effective from",
    until: "Effective until",
    valueKind: "Value kind",
    evidenceClass: "Evidence class",
    evidencePresent: "Evidence",
    evidenceAvailable: "A safe reference is recorded",
    evidenceMissing: "No reference is recorded",
    governedValue: "Governed value",
    invalidValue:
      "The value does not match the current strict format and is not displayed.",
    sourceReference: "Safe source reference",
    evidenceSummary: "Safe evidence summary",
    notRecorded: "Not recorded",
    requiredApprovals: "Required authorities",
    status: "Status",
    proposal: {
      title: "New proposal",
      intro:
        "Owner only. The JSON value is strictly validated for the selected authority; unknown fields and oversized content are rejected.",
      privileged: "Privileged editor—do not enter secrets, tokens, passwords, or personal data.",
      authority: "Authority",
      environment: "Explicit scope",
      value: "Strict JSON value",
      valueHelp:
        "Use only one of the value kinds shown for the selected authority. Status, actor, approver, and system evidence are never accepted from the browser.",
      sourceReference: "Safe source reference",
      sourceHelp: "Do not enter evidence contents or provider identifiers.",
      evidenceSummary: "Safe summary",
      internalNotes: "Internal note (never shown in the package)",
      effectiveFrom: "Effective from",
      effectiveUntil: "Effective until (optional)",
      submit: "Create proposal",
      pending: "Saving…",
    },
    actions: {
      submit: "Submit for review",
      approve: "Record approval",
      reject: "Reject",
      confirmationTitle: "Confirm governance action",
      submitDescription: "The record will move into formal review.",
      approveDescription:
        "A separate approval for the selected conceptual authority will be recorded. Production remains blocked until every dependency is complete.",
      rejectDescription: "The record will become terminally rejected.",
      decisionAuthority: "Approve as",
      evidenceReference: "Safe evidence reference",
      evidenceSummary: "Safe summary",
      cancel: "Cancel",
      confirm: "Confirm",
      pending: "Processing…",
    },
    actionResult: {
      success: "The action was appended to the immutable audit trail.",
      invalid: "The request is invalid or contains unexpected fields.",
      forbidden: "This action is not permitted.",
      conflict: "The record changed. Reload the page and try again.",
      dependencies: "Production GO is blocked by unapproved dependencies.",
      unavailable: "The action is temporarily unavailable.",
      rateLimited: "This action is temporarily limited. Try again later.",
    },
  },
} as const;
